"use server"

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function checkIn(geoInfo?: any) {
  const supabase = await createClient()

  // Verify auth
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  // Ensure no open session
  const { data: activeSession } = await supabase
    .from('timesheet_sessions')
    .select('id')
    .eq('user_id', user.id)
    .is('check_out_at', null)
    .single()

  if (activeSession) {
    throw new Error("You already have an active session. Check-out first.")
  }

  // Insert new session (time is generated by DB)
  // We don't have request IP easily in Server Actions without headers,
  // but we can pass it if we intercept in middleware, for now let's just pass geo.
  const { error } = await supabase
    .from('timesheet_sessions')
    .insert({
      user_id: user.id,
      check_in_at: new Date().toISOString(), // Fallback if DB doesn't set it, though schema has default now()
      check_in_geo: geoInfo || null,
      source: 'web'
    })

  if (error) {
    console.error(error)
    throw new Error("Failed to check in")
  }

  revalidatePath('/timesheet')
  return { success: true }
}

export async function checkOut(geoInfo?: any) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  // Find active session
  const { data: activeSession } = await supabase
    .from('timesheet_sessions')
    .select('id')
    .eq('user_id', user.id)
    .is('check_out_at', null)
    .single()

  if (!activeSession) {
    throw new Error("No active session found.")
  }

  const { error } = await supabase
    .from('timesheet_sessions')
    .update({
      check_out_at: new Date().toISOString(),
      check_out_geo: geoInfo || null
    })
    .eq('id', activeSession.id)

  if (error) {
    console.error(error)
    throw new Error("Failed to check out")
  }

  revalidatePath('/timesheet')
  return { success: true }
}

export async function updateWorklog(date: string, content_md: string, tags: string[]) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error("Unauthorized")

  // Upsert worklog for the day
  const { error } = await supabase
    .from('worklogs')
    .upsert({
      user_id: user.id,
      date,
      content_md,
      tags,
      updated_at: new Date().toISOString()
    }, { onConflict: 'user_id, date' })

  if (error) {
    console.error(error)
    throw new Error("Failed to update worklog")
  }

  revalidatePath('/timesheet')
  return { success: true }
}
